-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 18:17:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WebDiP2018x093
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2018x093
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2018x093` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2018x093` ;

-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`kategorije_licenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`kategorije_licenca` (
  `id_kategorije_licenca` INT NOT NULL AUTO_INCREMENT,
  `naziv_kategorije` VARCHAR(45) NOT NULL,
  `opis_kategorije` VARCHAR(500) NULL,
  `datum_azuriranja_kategorija` DATETIME NULL,
  PRIMARY KEY (`id_kategorije_licenca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`uloga_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`uloga_korisnika` (
  `id_uloga` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `kategorije_licenca_id_kategorije_licenca` INT NOT NULL,
  PRIMARY KEY (`id_uloga`),
  INDEX `fk_uloga_korisnika_kategorije_licenca1_idx` (`kategorije_licenca_id_kategorije_licenca` ASC)  ,
  CONSTRAINT `fk_uloga_korisnika_kategorije_licenca1`
    FOREIGN KEY (`kategorije_licenca_id_kategorije_licenca`)
    REFERENCES `WebDiP2018x093`.`kategorije_licenca` (`id_kategorije_licenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`dnevnik_rada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`dnevnik_rada` (
  `id_dnevnik_rada` INT NOT NULL AUTO_INCREMENT,
  `naslov_dnevnika` VARCHAR(45) NOT NULL,
  `opis_zahtjeva` VARCHAR(400) NOT NULL,
  `datum_unosa` DATE NOT NULL,
  `datum_azuriranja` DATETIME NULL,
  PRIMARY KEY (`id_dnevnik_rada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`korisnik` (
  `id_korisnik` INT NOT NULL AUTO_INCREMENT,
  `uloga_korisnika_id_uloga` INT NOT NULL,
  `dnevnik_rada_id_dnevnik_rada` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `email` TEXT NOT NULL,
  `datum_vrijeme_uvjeta` DATETIME NULL,
  PRIMARY KEY (`id_korisnik`),
  INDEX `fk_korisnik_uloga_idx` (`uloga_korisnika_id_uloga` ASC)  ,
  INDEX `fk_korisnik_dnevnik_rada1_idx` (`dnevnik_rada_id_dnevnik_rada` ASC)  ,
  CONSTRAINT `fk_korisnik_uloga`
    FOREIGN KEY (`uloga_korisnika_id_uloga`)
    REFERENCES `WebDiP2018x093`.`uloga_korisnika` (`id_uloga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_dnevnik_rada1`
    FOREIGN KEY (`dnevnik_rada_id_dnevnik_rada`)
    REFERENCES `WebDiP2018x093`.`dnevnik_rada` (`id_dnevnik_rada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`zahtjev_odobrenje_za_kupnju`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`zahtjev_odobrenje_za_kupnju` (
  `id_zahtjev_odobrenje` INT NOT NULL AUTO_INCREMENT,
  `status_zahtjeva` CHAR NOT NULL,
  `datum_odobrenja_odbijanja` DATETIME NOT NULL,
  `nasumicni_kljuc` INT NOT NULL,
  `kljuc_hidden_status` CHAR NOT NULL,
  PRIMARY KEY (`id_zahtjev_odobrenje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`zahtjev_vracanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`zahtjev_vracanje` (
  `id_zahtjev_vracanje` INT NOT NULL,
  `opis_razloga` VARCHAR(500) NOT NULL,
  `datum_predaje` DATETIME NOT NULL,
  `status_odobrenja` CHAR NOT NULL,
  `datum_odobrenja` DATETIME NOT NULL,
  PRIMARY KEY (`id_zahtjev_vracanje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`licence` (
  `id_licence` INT NOT NULL AUTO_INCREMENT,
  `kategorije_licenca_id_kategorije_licenca` INT NOT NULL,
  `zahtjev_odobrenje_id_zahtjev_odobrenje` INT NOT NULL,
  `zahtjev_vracanje_id_zahtjev_vracanje` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `slika_licence` VARCHAR(45) NULL,
  `kolicina` INT NOT NULL,
  `iznos` DECIMAL NOT NULL,
  `datum_stvaranja` DATE NOT NULL,
  `datum_isteka` DATE NOT NULL,
  PRIMARY KEY (`id_licence`),
  INDEX `fk_licence_kategorije_licenca1_idx` (`kategorije_licenca_id_kategorije_licenca` ASC)  ,
  INDEX `fk_licence_zahtjev_odobrenje1_idx` (`zahtjev_odobrenje_id_zahtjev_odobrenje` ASC)  ,
  INDEX `fk_licence_zahtjev_vracanje1_idx` (`zahtjev_vracanje_id_zahtjev_vracanje` ASC)  ,
  CONSTRAINT `fk_licence_kategorije_licenca1`
    FOREIGN KEY (`kategorije_licenca_id_kategorije_licenca`)
    REFERENCES `WebDiP2018x093`.`kategorije_licenca` (`id_kategorije_licenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_licence_zahtjev_odobrenje1`
    FOREIGN KEY (`zahtjev_odobrenje_id_zahtjev_odobrenje`)
    REFERENCES `WebDiP2018x093`.`zahtjev_odobrenje_za_kupnju` (`id_zahtjev_odobrenje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_licence_zahtjev_vracanje1`
    FOREIGN KEY (`zahtjev_vracanje_id_zahtjev_vracanje`)
    REFERENCES `WebDiP2018x093`.`zahtjev_vracanje` (`id_zahtjev_vracanje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`korisnik_has_licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`korisnik_has_licence` (
  `korisnik_id_korisnik` INT NOT NULL,
  `licence_id_licence` INT NOT NULL,
  INDEX `fk_korisnik_has_licence_licence1_idx` (`licence_id_licence` ASC)  ,
  INDEX `fk_korisnik_has_licence_korisnik1_idx` (`korisnik_id_korisnik` ASC)  ,
  CONSTRAINT `fk_korisnik_has_licence_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES `WebDiP2018x093`.`korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_has_licence_licence1`
    FOREIGN KEY (`licence_id_licence`)
    REFERENCES `WebDiP2018x093`.`licence` (`id_licence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`statistika_zahtjeva_kupnje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`statistika_zahtjeva_kupnje` (
  `id_statistika_zahtjeva_kupnje` INT NOT NULL,
  `kategorije_licenca_id_kategorije_licenca` INT NOT NULL,
  `licence_id_licence` INT NOT NULL,
  `zahtjev_odobrenje_id_zahtjev_odobrenje` INT NOT NULL,
  PRIMARY KEY (`id_statistika_zahtjeva_kupnje`),
  INDEX `fk_statistika_zahtjeva_kupnje_kategorije_licenca1_idx` (`kategorije_licenca_id_kategorije_licenca` ASC)  ,
  INDEX `fk_statistika_zahtjeva_kupnje_licence1_idx` (`licence_id_licence` ASC)  ,
  INDEX `fk_statistika_zahtjeva_kupnje_zahtjev_odobrenje1_idx` (`zahtjev_odobrenje_id_zahtjev_odobrenje` ASC)  ,
  CONSTRAINT `fk_statistika_zahtjeva_kupnje_kategorije_licenca1`
    FOREIGN KEY (`kategorije_licenca_id_kategorije_licenca`)
    REFERENCES `WebDiP2018x093`.`kategorije_licenca` (`id_kategorije_licenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statistika_zahtjeva_kupnje_licence1`
    FOREIGN KEY (`licence_id_licence`)
    REFERENCES `WebDiP2018x093`.`licence` (`id_licence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statistika_zahtjeva_kupnje_zahtjev_odobrenje1`
    FOREIGN KEY (`zahtjev_odobrenje_id_zahtjev_odobrenje`)
    REFERENCES `WebDiP2018x093`.`zahtjev_odobrenje_za_kupnju` (`id_zahtjev_odobrenje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`pruzitelji_licenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`pruzitelji_licenca` (
  `id_pruzitelji_licenca` INT NOT NULL,
  `naziv_pruzatelja` VARCHAR(45) NOT NULL,
  `kontakt_broj_pruzatelja` VARCHAR(20) NOT NULL,
  `opis_domene_licenci` VARCHAR(500) NULL,
  PRIMARY KEY (`id_pruzitelji_licenca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x093`.`zahtjev_za_nabavu_nove_licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x093`.`zahtjev_za_nabavu_nove_licence` (
  `id_zahtjev_za_nabavu_nove_licence` INT NOT NULL,
  `korisnik_id_korisnik` INT NOT NULL,
  `pruzitelji_licenca_id_pruzitelji_licenca` INT NOT NULL,
  `datum_podnosenja` DATETIME NOT NULL,
  `naziv_licence` VARCHAR(60) NOT NULL,
  `odobrenje_zahtjeva` CHAR NOT NULL,
  `opis_licence` VARCHAR(500) NULL,
  PRIMARY KEY (`id_zahtjev_za_nabavu_nove_licence`),
  INDEX `fk_zahtjev_za_nabavu_nove_licence_korisnik1_idx` (`korisnik_id_korisnik` ASC)  ,
  INDEX `fk_zahtjev_za_nabavu_nove_licence_pruzitelji_licenca1_idx` (`pruzitelji_licenca_id_pruzitelji_licenca` ASC)  ,
  CONSTRAINT `fk_zahtjev_za_nabavu_nove_licence_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES `WebDiP2018x093`.`korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zahtjev_za_nabavu_nove_licence_pruzitelji_licenca1`
    FOREIGN KEY (`pruzitelji_licenca_id_pruzitelji_licenca`)
    REFERENCES `WebDiP2018x093`.`pruzitelji_licenca` (`id_pruzitelji_licenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
